apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aiops-hub.fullname" . }}
  labels:
    {{- include "aiops-hub.labels" . | nindent 4 }}
data:
  AIOPS_ENVIRONMENT: {{ .Values.app.environment | quote }}
  AIOPS_COMMAND_TIMEOUT_SECONDS: {{ .Values.app.commandTimeoutSeconds | quote }}
  AIOPS_ENABLE_OPENAI_ENRICHMENT: {{ .Values.app.enableOpenAIEnrichment | quote }}
  AIOPS_OPENAI_MODEL: {{ .Values.app.openaiModel | quote }}
  AIOPS_REQUIRE_API_KEY: {{ .Values.app.requireApiKey | quote }}
  AIOPS_STATE_DB_PATH: {{ .Values.app.stateDbPath | quote }}
