apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiops-hub.fullname" . }}
  labels:
    {{- include "aiops-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIOPS_OPENAI_API_KEY: {{ .Values.openai.apiKey | quote }}
  AIOPS_API_KEYS_ADMIN: {{ .Values.keys.admin | quote }}
  AIOPS_API_KEYS_OPERATOR: {{ .Values.keys.operator | quote }}
  AIOPS_API_KEYS_VIEWER: {{ .Values.keys.viewer | quote }}
